name: golang
on: [push]
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout/@v2

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: build
      run: go build -v ./...
